### ISSUE TITLE
EXAM

### ISSUE THREAD

**Issue by kuznetsovandrey76** [kuznetsovandrey76/Yaroslavl-Demidov-State-University#1]
- [ ] Раздел 2. [Алгебра и геометрия](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/5) - [**book1**](https://yadi.sk/i/Lq3ZGhyG3T9nnY)
- [ ] Раздел 3. [Дискретная математика и математическая логика](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/3)
- [ ] Раздел 1. [Математический анализ](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/2)
- [ ] Раздел 7. [Теория вероятностей и статистика](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/9)
- [ ] Раздел 5. [Информатика и программирование](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/6)
- [x] Раздел 4. [Базы данных](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/7)
- [ ] Раздел 6. [Компьютерные сети](https://github.com/kuznetsovandrey76/Yaroslavl-Demidov-State-University/issues/8)

[вступительный экзамен](https://yadi.sk/i/ajWlG-fp3TBbHY)
